### ISSUE TITLE
Code import wards trả về sai id lúc đầu

### ISSUE THREAD

**Issue by vietdm98** [hoangphidev/vietnam-maps#2]
Hiện tượng: Khi thực hiện download và import xã/phường/thị trấn đang trả về sai id của distict
Cụ thể: ở file vendor/hoangphi/vietnam-maps/src/Imports/VietnamMapImport.php:111 thì đang trả về $provinceId mà đúng ra phải là $districtId
Xác nhận: Sau khi thực hiện thay đổi code tôi đã có đúng wards mong muốn. Nhờ dev check lại code!

**Comment by hoangphidev** [comment]
Sai id lúc đầu là sao bạn nhỉ?

**Comment by hoangphidev** [comment]
Cảm ơn bạn đã đóng góp. Mình sẽ fix và cập nhật lại 😄

**Comment by vietdm98** [comment]
đây là ảnh code lúc đầu
![image](https://user-images.githubusercontent.com/55265675/104799077-b1ba0500-57fe-11eb-8fbe-bb77c6951b97.png)

Đây là kết quả import. district_id của Phường Phú Thượng phải = 3 (Quận Tây Hồ) nhưng nó lại là 1 (theo code thì là của province_id = 1 (Hà Nội) => sai cấu trúc
![image](https://user-images.githubusercontent.com/55265675/104799109-f180ec80-57fe-11eb-83ee-c615b6b5315e.png)

Đây là code sau khi sửa
![image](https://user-images.githubusercontent.com/55265675/104799122-20975e00-57ff-11eb-81e9-5de2d0865dc1.png)

Kết quả database đã có cấu trúc đúng!
![image](https://user-images.githubusercontent.com/55265675/104799139-3ad13c00-57ff-11eb-8fd5-6faa0ba95917.png)

**Comment by vietdm98** [comment]
Mình đã comment lại đấy. Bạn xem qua

Vào 13:24, Th 7, 16 thg 1, 2021 Phi Hoang <notifications@github.com> đã
viết:

**Comment by hoangphidev** [comment]
Ok bạn.
