### ISSUE TITLE
please add support for laravel 10

### ISSUE THREAD

**Issue by tungnguyenls2008** [hoangphidev/vietnam-maps#7]
I tried to install your package into my laravel 10 project and got conflicted, please add support for laravel 10.
Thank you so much in advance, bro!

**Comment by hoangphidev** [comment]
Hi @tungnguyenls2008, 

I just updated to the latest version that supports laravel 10. You can redo the new installation. If there are no other problems, I would like to close this issue. Thank you for your contributions.

https://prnt.sc/pXcmJLQX8swk
